name: Step3 Code Review

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  claude-review:
    if: |
      (github.event_name == 'pull_request' && (
        contains(github.event.pull_request.title, 'step3') ||
        contains(github.event.pull_request.title, 'Step3') ||
        contains(github.event.pull_request.title, '3단계') ||
        contains(github.event.pull_request.labels.*.name, 'step3')
      )) ||
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body, '@claude review'))

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-2

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          use_bedrock: true
          timeout_minutes: '30'
          model: 'apac.anthropic.claude-sonnet-4-20250514-v1:0'

          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            ## 🎯 Step 3 미션 달성도 중심 리뷰 가이드라인
            
            **이 리뷰는 Step 3 미션 요구사항 달성에 집중합니다.**
            JsonView 클래스 구현과 Legacy MVC 제거를 중점적으로 검토하고 **한글로** 피드백을 제공해주세요.
            
            ### 📚 학습 원칙
            - **직접 코드를 제공하지 마세요** (학습자가 명시적으로 요청하는 경우 제외)
            - **문제 해결 과정을 안내**하되, 정답을 바로 알려주지 마세요
            - **작은 단계로 문제를 분해**하여 접근하도록 도와주세요
            
            ### 💡 피드백 방법
            - **유도 질문 활용**: "만약 ~라면 어떻게 될까요?", "~를 고려해보셨나요?"
            - **힌트 제공**: 방향은 제시하되, 구체적인 구현은 학습자가 하도록
            - **다양한 접근법 제시**: 한 가지 해결책이 아닌 여러 가능성을 제안
            - **왜?에 집중**: 단순히 무엇이 잘못되었는지보다 왜 그런지 이해하도록
            
            ### 🔍 디버깅 독립성 강화
            - 에러 메시지를 **스스로 읽고 이해**하도록 격려
            - 로그 활용법 안내 (System.out.println, logger, 디버거 활용)
            - 문제 패턴 파악을 도와 **디버깅 스킬 향상**
            - 관련 문서나 JavaDoc 참조 권장
            
            ### 📋 미션 달성도 체크리스트
            
            #### 1. JsonView 클래스 구현
            - [ ] Jackson 라이브러리를 사용한 JSON 직렬화 구현
            - [ ] ContentType을 APPLICATION_JSON_UTF8_VALUE로 설정
            - [ ] model 데이터 1개는 값 그대로, 2개 이상은 Map 형태로 JSON 변환
            - [ ] View 인터페이스를 구현하여 render 메서드 정의
            
            #### 2. Legacy MVC 완전 제거
            - [ ] app 모듈의 모든 컨트롤러를 어노테이션 기반 MVC로 변경
            - [ ] asis 패키지의 레거시 코드 삭제 후 서비스 정상 동작 확인
            - [ ] DispatcherServlet을 app 패키지에서 mvc 패키지로 이동
            - [ ] UserController 추가하여 JSON API 동작 테스트
            
            ### 🎓 핵심 학습 포인트
            - **뷰 계층의 확장**: JSP와 JSON 등 다양한 응답 형태를 지원하는 방법
            - **라이브러리 활용**: Jackson을 통한 객체-JSON 직렬화 처리
            - **레거시 코드 제거**: 기존 코드를 안전하게 제거하는 리팩터링 전략
            - **모듈 간 의존성**: app과 mvc 모듈 간의 적절한 책임 분리
            - **API 설계**: RESTful한 JSON API 엔드포인트 구현
            
            ### 🌟 학습 완료 후
            - "이번 구현을 통해 무엇을 배우셨나요?" 같은 **회고 질문**
            - 비슷한 문제를 만났을 때 적용 가능한 **패턴 인식**
            - 다음 단계 학습을 위한 **추가 학습 자료** 제안
            
            ### ⚠️ 예외 상황
            - 학습자가 "코드를 보여주세요" 등 **명시적으로 요청**시에만 코드 제공
            - 개념 설명 요청시 (예: "서블릿이 뭔가요?") **명확하고 직접적인 설명** 제공
            
            **리뷰는 건설적이고 격려하는 톤으로 작성하며, 학습자의 성장을 최우선으로 고려해주세요.**
